function out= replace_syllable_data_in_table(syllable,filename,table)
% replace syllable data "syllable" recorded in "filename"
% in mysql "table".
% out=replace_syllable_data(syllable,filename,table)
% syllable is a struct which contains the following information.
% 
%     'serial_number',...
%     'bird_ID',...
%     'start_on',...
%     'duration',...
%     'mean_pitch',...
%     'mean_FM',...
%     'mean_entropy',...
%     'mean_goodness_of_pitch',...
%     'mean_mean_frequency',...
%     'mean_am2',...
%     'mean_amplitude',...
%     'var_pitch',...
%     'var_FM',...
%     'var_entropy',...
%     'var_goodness_of_pitch',...
%     'var_mean_frequency',...
%     'var_am',...
%     'month',...
%     'day',...
%     'hour',...
%     'minute',...
%     'second',...
%     'cluster',...
%     'trial',...
%     'stimulated';
% 
%     filename: wav name ending with .wav.
%     table   : mysql table name.
% 
% 
% out is successful (1) or not (0).
% 
% 
% 
%  ex) 
% 
% by KH 20101210

conn = database('mysql', '', '');

if nargin<3
    error('Plase define the database!: ');
end

upload_columns={...
    'serial_number',...
    'bird_ID',...
    'start_on',...
    'duration',...
    'mean_pitch',...
    'mean_FM',...
    'mean_entropy',...
    'mean_goodness_of_pitch',...
    'mean_mean_frequency',...
    'mean_am2',...
    'mean_amplitude',...
    'var_pitch',...
    'var_FM',...
    'var_entropy',...
    'var_goodness_of_pitch',...
    'var_mean_frequency',...
    'var_am',...
    'month',...
    'day',...
    'hour',...
    'minute',...
    'second',...
    'cluster',...
    'trial',...
    'stimulated'};

%      'file_name',... is removed from the list because it is
%      char, but it is uploaded.
delete_clause=sprintf('DELETE FROM %s WHERE file_name=''%s''',...
    table,filename);
exec(conn,delete_clause);
commit(conn);

%             h = waitbar(0,'Uploading cluster data...');
for kk=1:length(syllable)
    insertClause=sprintf('INSERT INTO %s ', table  );
    varnameClause   =sprintf('%s,',upload_columns{:});
    varnameClause= ['(recnum,' varnameClause, 'file_name)'];
    varvalClause = sprintf(' VALUES (NULL,%d,',syllable(kk).serial_number);
    for ll=2:length(upload_columns)
        varvalClause   =[varvalClause, sprintf('%g,',syllable(kk).(upload_columns{ll}))];
    end
    varvalClause= sprintf('%s''%s'')',varvalClause,filename);
    %                  stim_tClause=sprintf('%g,',syllable(kk).stim_t);
    %                  stim_tClause=['(',stim_tClause(1:end-1),')']
    exec(conn,[insertClause,varnameClause,varvalClause]);
end
commit(conn);
%         set(conn,'AutoCommit','on');
%              close(h);
close(conn);
