% analysis_parameters 
% 
% to be used in the song classification and parsing structure.
%

converting_matrix={
    'x',... % 0 unclassified note
    'i',... % 1introductory note
    'a',... % 2
    'b',... % 3
    'c',... % 4
    'd',... % 5
    'e',... % 6
    'f',... % 7
    'g',... % 8
    'n'};% 9, noise

% %The rule here is not to change the number of characters. 
% %Here is an example of replacing chart which uses regular expression.
% 
% replace_chart={...
%     'eib',    'eab';... % ieeeeib is actually same as ia
%     'i(e*)eb',     'i$1ab';...
%     'abid',     'abcd';...% abid, this 'i' is actually 'c'.
%     'i(e*)eab',    'i$1Nab';...
%     'eabi',    'eabc';...
%     'abi',    'abc';...
%     'bide',   'bcde';...
%     'fbi',   'fbc';...
%     'iiici', 'iiiii';,...
%   };% 9, noise

% The rule here is not to change the number of characters. 
replace_chart={};%



replace_repeats_chart={...
    'iii+',   'iii';...
    'a+',   'a';...
    'b+',   'b';...
    'c+',   'c';...
    'd+',   'd';...
    'e+',   'e';...
    'f+',   'f';...
    'g+',   'g';...
    'h+',   'h';...
    'N',    '';... % remove noise
    };